### ISSUE TITLE
Category items "Posts" and "Tags" are kind of floating

### ISSUE THREAD

**Issue by cellio** [mattjbrent/mattjbrent.github.io#1]
There are global links, which are in the blue header (or the user widget).  There are categories, which are visibly "tabs".  Under the categories and above the category description, there are category-specific links -- posts, tags, and ask question.  To my eye these are kind of "floating" and not obviously about the category.  I don't know what presentation would be clearer; the current design puts those all in a stripe of the same color as the selected category tab, so that's clear, but this design has a "lighter" look and doesn't use color or stripes in that way.  So this is a vague "we need to do something" issue without any concrete ideas, sorry.

Don't know -- maybe if "posts" and "tags" were flush right, to the left of the "ask" button, and there were a thin rule under them all or something?  I am not a designer...

**Comment by mattjbrent** [comment]
No i think it needs to be left - i just feel like its not considered or anchored right now. Ive just pushed a few changes that I feel address this issue. Im trying to avoid banding everything together at the top and locate items in the areas that are related to each other. 

This moves the items down but makes the page easier to navigate. It wasnt quite there before but i feel this iteration is stronger. It also fixes an issue where the selected default page (posts) wasnt correctly stylised

**Comment by mattjbrent** [comment]
im closing this out feel free to open another or reopen this if necessary

**Comment by cellio** [comment]
Oh that's much clearer, thanks.  Yes, we need to clearly indicate that these items go with the category, not the whole community.  The new positioning makes that clear.
