### ISSUE TITLE
Please add "edits" alongside "posts" and "tags"

### ISSUE THREAD

**Issue by cellio** [mattjbrent/mattjbrent.github.io#2]
There's one more category-specific item shown on all categories, "edits".  Could you please add it?  In addition to showing the expected spacing a little more, eventually we should think about some way of signalling that there are suggested edits pending, so having it there might elicit some ideas.

**Comment by mattjbrent** [comment]
Would this be a use-case for using the notifications system? are you suggesting having some kind of icon in situ?

ill close this out - feel free to expand on that as a new issue as it sounds interesting and deserves its own ticket i think

**Comment by cellio** [comment]
Didn't mean to scope-creep your prototype, sorry.  You know how categories show that gray circle when there are new posts?  I want us to do something like that next to "Edits" when there are suggested edits pending review.  But we probably only want to show it to people who can do those reviews, so in that sense it's different.  I also don't have an opinion about what the indictor should be fore any of these.  We can tackle that later.
